apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
  namespace: monitoring
spec:
  selector:
    app: alertmanager-deployment
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
