apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  labels:
    app: alertmanager-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-deployment
  template:
    metadata:
      name: alertmanager-deployment
      labels:
        app: alertmanager-deployment
    spec:
      initContainers:
      - args:
        - sh
        - -c
        - cat /config.yml | envsubst > /etc/alertmanager/config.yml
        image: bhgedigital/envsubst
        name: envsubst
        env:
          - name: GMAIL_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: alertmanager-smtp-secret
                key: user_account
          - name: GMAIL_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: alertmanager-smtp-secret
                key: secret_key
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
        volumeMounts:
          - mountPath: /etc/alertmanager
            name: alertmanager-volume
          - mountPath: /config.yml
            subPath: config.yml
            name: alertmanager-volume-configmap
      containers:
        - name: alertmanager-deployment
          image: prom/alertmanager:v0.19.0          
          args:
            - "--config.file=/etc/alertmanager/config.yml"
            - "--storage.path=/alertmanager"
          ports:
            - name: http
              containerPort: 9093
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:            
            - name: alertmanager-templates-volume
              mountPath: /etc/alertmanager-templates
            - name: alertmanager-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: alertmanager-volume
          emptyDir: {}
        - name: alertmanager-volume-configmap
          configMap:
            name: alertmanager-configmap
        - name: alertmanager-templates-volume
          configMap:
            name: alertmanager-templates-configmap
        
