apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: alert_rules
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
      - alert: DiskSpaceFree10Percent
        expr: node_filesystem_free_percent <= 10
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} has 10% or less Free disk space."
          description: "{{ $labels.instance }} has only {{ $value }}% or less free."
    - name: custom_rules
      rules:
        - record: node_memory_MemFree_percent
          expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)
        - record: node_filesystem_free_percent
          expr: 100 * node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alert-manager-service.monitoring.svc:9093
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - prometheus-service.monitoring.svc:9090
      - job_name: node_exporter
        static_configs:
          - targets:
              - node-exporter-service.monitoring.svc:9100
      - job_name: alert_manager
        static_configs:
          - targets:
              - alertmanager-service.monitoring.svc:9093
