apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: example
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 192.168.56.10:31000
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - 192.168.56.10:31965
      - job_name: node
        static_configs:
          - targets:
              - 192.168.56.10:30285
