apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  prometheus.example.com;
          location / {
            proxy_pass http://192.168.56.10:32647;
        }
      }
    }