apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 80
      targetPort: 9100
      nodePort: 30285
