apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  namespace: monitoring
spec:
  selector:
    app: grafana-deployment
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
